name: No Java CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]
    steps:
    - uses: actions/checkout@v1
    - name: Synopsys Detect Action
      id: detect
      uses: gautambaghel/synopsys-detect-js@master
      with:
        args: --blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}"
