name: Java CI

on: [push]

jobs:
  buildU:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, macos-latest, windows-2019, windows-2016]
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Synopsys Detect Action
      id: detect
      uses: gautambaghe/synopsys-detect-js@master
      with:
        args: --blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}"
    - name: Get the detect output time
      run: echo "The time was ${{ steps.detect.outputs.time }}"
